In [127]:
#data encoding >> converting categorical columns into numeric
#Nominal/OHE
#label and ordinal encoding
#Target guided ordinal encoding
#Nominal/OHE >> Binary vector for each of the categories
#example single, married, separated
#single: [1, 0, 0]
#married: [0, 1, 0]
#separated: [0, 0, 1]

In [128]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


In [129]:
df=pd.DataFrame({'status': ['single', 'married', 'separated','single','married']})

In [130]:
df

,status
0,single
1,married
2,separated
3,single
4,married


In [131]:
encoder=OneHotEncoder()

In [132]:
encoder

,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",None
,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a :class:`scipy.sparse.csr_matrix`,i.e. a sparse matrix in ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",True
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide `.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'error'
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide `.",None
,"max_catego

In [133]:
encoded=encoder.fit_transform(df[['status']]).toarray() #type:ignore

In [134]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [135]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [136]:
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [137]:
encoded_df

,status_married,status_separated,status_single
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0


In [138]:
encoder.transform([['single']]).toarray() #type:ignore

e:\PW skills\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [139]:

hw_df=pd.get_dummies(df)
hw_df

,status_married,status_separated,status_single
0,False,False,True
1,True,False,False
2,False,True,False
3,False,False,True
4,True,False,False


In [140]:
pd.concat([df,encoded_df],axis=1)

,status,status_married,status_separated,status_single
0,single,0.0,0.0,1.0
1,married,1.0,0.0,0.0
2,separated,0.0,1.0,0.0
3,single,0.0,0.0,1.0
4,married,1.0,0.0,0.0


In [141]:
import seaborn as sns
tips = sns.load_dataset('tips')


In [142]:
day_df = tips[['day']].copy()

In [143]:
day_encoder = OneHotEncoder(sparse_output=False, dtype=int)
day_encoded = day_encoder.fit_transform(day_df)

In [144]:
tips_encoded_df = pd.DataFrame(
    day_encoded,
    columns=day_encoder.get_feature_names_out(),
    index=day_df.index,
 )

In [145]:
tips_encoded_df

,day_Fri,day_Sat,day_Sun,day_Thur
0,0,0,1,0
1,0,0,1,0
2,0,0,1,0
3,0,0,1,0
4,0,0,1,0
...,...,...,...,...
239,0,1,0,0
240,0,1,0,0
241,0,1,0,0
242,0,1,0,0


In [146]:
another_tips_dummy = pd.get_dummies(day_df['day'], prefix='day', dtype=int)

In [147]:
another_tips_dummy

,day_Thur,day_Fri,day_Sat,day_Sun
0,0,0,0,1
1,0,0,0,1
2,0,0,0,1
3,0,0,0,1
4,0,0,0,1
...,...,...,...,...
239,0,0,1,0
240,0,0,1,0
241,0,0,1,0
242,0,0,1,0


In [148]:
#label encoding >> assign unique label to the categories
# using map or using library

In [149]:
df

,status
0,single
1,married
2,separated
3,single
4,married


In [150]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [151]:
label_encoder.fit_transform(df['status'])   

array([2, 0, 1, 2, 0])

In [152]:
label_encoder.transform([["separated"]])

e:\PW skills\Machine Learning\ml_env\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [153]:
#ordinal encoding

#High school : 1
#gradiate: 2
#post graduate: 3
#Phd: 4

In [154]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({"qualification": ["HS","GR", "PG", "PHD", "HS", "PHD"]})

In [155]:
df

,qualification
0,HS
1,GR
2,PG
3,PHD
4,HS
5,PHD


In [156]:
encoder = OrdinalEncoder(categories=[["HS", "GR", "PG", "PHD"]])


In [157]:
encoder.fit_transform(df[["qualification"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [158]:
#new data
encoder.transform([["PG"]]) #type:ignore

e:\PW skills\Machine Learning\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [159]:
#Target guided ordinal encoding
#relationship with target variable
#A lot of unique categories
#replace the category with mean and median of respective group

In [160]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [161]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [162]:
df['time_encoded'] = df['time'].map(mean_price)

In [163]:
df

,time,total_bill,time_encoded
0,lunch,120,135.000000
1,breakfast,130,153.333333
2,dinner,90,156.333333
3,lunch,125,135.000000
4,breakfast,150,153.333333
5,dinner,190,156.333333
6,lunch,160,135.000000
7,breakfast,180,153.333333
8,dinner,189,156.333333


In [164]:
sns.load_dataset("tips")

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [165]:
tips=sns.load_dataset("tips")

In [166]:
tips_df=pd.DataFrame(tips[['time', 'total_bill']])

In [167]:
mean_price = tips_df.groupby('time')['total_bill'].mean().to_dict()

In [168]:
tips_df['time_encoded'] = tips_df['time'].map(mean_price)

In [169]:
tips_df

,time,total_bill,time_encoded
0,Dinner,16.99,20.797159
1,Dinner,10.34,20.797159
2,Dinner,21.01,20.797159
3,Dinner,23.68,20.797159
4,Dinner,24.59,20.797159
...,...,...,...
239,Dinner,29.03,20.797159
240,Dinner,27.18,20.797159
241,Dinner,22.67,20.797159
242,Dinner,17.82,20.797159
