In [1]:
import numpy as np

In [2]:
a=np.zeros((3,4))

In [3]:
a.ndim

2

In [4]:
np.zeros(10,dtype='float16')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float16)

In [5]:
np.ones((2,3,4),dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [6]:
arr=np.zeros((2,3,4,5))

In [7]:
arr

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [8]:
arr.ndim

4

In [9]:
arr+5

array([[[[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]],

        [[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]],

        [[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]]],


       [[[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]],

        [[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]],

        [[5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5.]]]])

In [10]:
(arr+5)*2

array([[[[10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.]],

        [[10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.]],

        [[10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.]]],


       [[[10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.]],

        [[10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.]],

        [[10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.],
         [10., 10., 10., 10., 10.]]]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.empty((2,3))

array([[3.50786609e-322, 6.95170131e-310, 4.94065646e-324],
       [            nan, 0.00000000e+000, 1.94693963e-308]])

In [13]:
import random

In [14]:
random.choice([1,2,3,4,5])

3

In [15]:
random.randrange(2,10)

6

In [16]:
random.random()

0.9145247125606754

In [17]:
lis=[1,2,3,4,5]

In [18]:
random.shuffle(lis)
lis

[1, 2, 3, 4, 5]

In [19]:
random.uniform(7,14)

7.260049547978203

In [20]:
np.array([])

array([], dtype=float64)

In [21]:
np.random.random_sample()

0.022950731639796662

In [22]:
np.random.random_sample((2,3))

array([[0.72234805, 0.02103714, 0.5747633 ],
       [0.70540385, 0.56772767, 0.4808765 ]])

In [23]:
np.random.randn(3,4)

array([[ 0.20430013,  1.20313114, -0.46503651, -0.82657308],
       [ 0.64243282,  0.31959258,  0.26011364, -0.43125699],
       [ 0.28189873, -0.9633698 ,  2.44342047, -0.58840162]])

In [25]:
arr=np.random.randint(2,10,size=(3,4))

In [27]:
arr.reshape(6,2)

array([[5, 5],
       [7, 6],
       [9, 2],
       [9, 2],
       [7, 7],
       [5, 2]], dtype=int32)

In [28]:
arr.reshape(4,-1)

array([[5, 5, 7],
       [6, 9, 2],
       [9, 2, 7],
       [7, 5, 2]], dtype=int32)

In [30]:
arr1=np.random.randint(1,10,(5,6))

In [31]:
arr1.size



30

In [32]:
arr1>3

array([[ True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False],
       [False, False,  True,  True,  True, False]])

In [34]:
arr2=arr1>3
arr2

array([[ True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False],
       [False, False,  True,  True,  True, False]])

In [35]:
arr1[arr1>3]

array([5, 7, 5, 7, 6, 5, 9, 8, 4, 9, 8, 7, 9, 7, 7, 9, 5, 8, 6, 4, 9, 6,
       4, 5], dtype=int32)

In [36]:
arr1


array([[5, 7, 5, 7, 6, 5],
       [2, 9, 8, 4, 9, 3],
       [8, 7, 9, 7, 7, 9],
       [5, 8, 6, 4, 9, 3],
       [1, 3, 6, 4, 5, 3]], dtype=int32)

In [37]:
arr1[0]

array([5, 7, 5, 7, 6, 5], dtype=int32)

In [38]:
arr1[0:3][:2]

array([[5, 7, 5, 7, 6, 5],
       [2, 9, 8, 4, 9, 3]], dtype=int32)

In [39]:
arr1[0:3,2:5]

array([[5, 7, 6],
       [8, 4, 9],
       [9, 7, 7]], dtype=int32)

In [40]:
arr2=np.random.randint(1,20,(5,6))

In [41]:
arr1+arr2

array([[ 9, 13, 16, 22, 14, 11],
       [ 4, 20, 12, 22, 20, 13],
       [16, 21, 26, 10, 11, 21],
       [ 9, 18, 15, 20, 23, 14],
       [20, 10, 15, 22,  6, 12]], dtype=int32)

In [42]:
arr1-arr2

array([[  1,   1,  -6,  -8,  -2,  -1],
       [  0,  -2,   4, -14,  -2,  -7],
       [  0,  -7,  -8,   4,   3,  -3],
       [  1,  -2,  -3, -12,  -5,  -8],
       [-18,  -4,  -3, -14,   4,  -6]], dtype=int32)

In [43]:
arr1*arr2

array([[ 20,  42,  55, 105,  48,  30],
       [  4,  99,  32,  72,  99,  30],
       [ 64,  98, 153,  21,  28, 108],
       [ 20,  80,  54,  64, 126,  33],
       [ 19,  21,  54,  72,   5,  27]], dtype=int32)

In [44]:
arr1/arr2

array([[1.25      , 1.16666667, 0.45454545, 0.46666667, 0.75      ,
        0.83333333],
       [1.        , 0.81818182, 2.        , 0.22222222, 0.81818182,
        0.3       ],
       [1.        , 0.5       , 0.52941176, 2.33333333, 1.75      ,
        0.75      ],
       [1.25      , 0.8       , 0.66666667, 0.25      , 0.64285714,
        0.27272727],
       [0.05263158, 0.42857143, 0.66666667, 0.22222222, 5.        ,
        0.33333333]])

In [ ]:
arr1 @ arr2 # doesn't fit for matrix multiplication

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 6)

In [46]:
arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(3,4))

In [47]:
arr1 @ arr2

array([[32, 74, 38, 50],
       [40, 72, 76, 45]], dtype=int32)

In [48]:
np.dot(arr1,arr2)

array([[32, 74, 38, 50],
       [40, 72, 76, 45]], dtype=int32)

In [49]:
arr1.T


array([[6, 1],
       [2, 1],
       [2, 8]], dtype=int32)

In [50]:
arr1

array([[6, 2, 2],
       [1, 1, 8]], dtype=int32)