In [75]:
import numpy as np

In [76]:
np.__version__

'2.1.2'

In [77]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [78]:
lis=[1,2,3,"pwskills",True,5.6]
type(lis)

list

In [79]:
l=[1,2,3,4,5]

In [80]:
arr=np.array(l)

In [81]:
arr


array([1, 2, 3, 4, 5])

In [82]:
type(arr)

numpy.ndarray

In [83]:
np.array(lis)

array(['1', '2', '3', 'pwskills', 'True', '5.6'], dtype='<U32')

In [84]:
type(np.array(lis))

numpy.ndarray

In [85]:
np.array(lis).ndim

1

In [86]:
arr1=np.array([[1,2,3],[4,5,6]])

In [87]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr1.ndim

2

In [89]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [90]:
mat=np.matrix(arr1)

In [91]:
type(mat)

numpy.matrix

In [92]:
np.matrix([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

ValueError: matrix must be 2-dimensional

In [ ]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
t=([1,2,3],[4,5,6])

In [ ]:
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr=np.fromfunction(lambda i,j:i+j, (3,3),dtype=int)

In [ ]:
arr.shape

(3, 3)

In [ ]:
np.fromfunction(lambda i,j:i*j, (3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [ ]:
iterator=(x**2 for x in range(5))

In [ ]:
np.fromiter(iterator, dtype=int, count=5)

array([ 0,  1,  4,  9, 16])

In [ ]:
np.fromstring('1 2 3 4 5', dtype=int, sep=' ')

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

AttributeError: module 'numpy' has no attribute 'linespace'